services:
  - type: web
    name: lucrai-site
    runtime: docker
    dockerfilePath: ./backend/src/Lucrai.API/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__Default
        sync: false
      - key: Jwt__Key
        sync: false
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: true
      - key: Jwt__Issuer
        value: lucrai-api
      - key: Jwt__Audience
        value: lucrai-frontend
      - key: Cors__Origins
        value: https://lucrai-site.vercel.app
